#APP_NAME
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/category/**
          filters:
           - name: CircuitBreaker
             args:
              name: category-service
              fallbackurl: forward:/categoryFallBack
#PORT
server:
  port: 9091

#EUREKA
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

ribbon.ReadTimeout=100000

ribbon.ConnectTimeout=100000

