#PORT
server:
  port: 7001
  
#APP_NAME
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/category/**
          filters:
           - name: CircuitBreaker
             args:
              name: category-service
              fallbackurl: forward:/categoryFallBack
#SECURITY      
  security:
    oauth2:
      client:
        client-id: mobile
        client-secret: pin
        user-authorization-uri: http://localhost:9191/oauth/authorize
        access-token-uri: http://localhost:9191/oauth/token
      resource:
        token-info-uri: http://localhost:9191/oauth/check_token
        
  servlet:
    session:
      cookie:
        name: KSESSION 

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
            
#http://localhost:7001/actuator/hystrix.stream   
         
