#PORT
server:
  port: 8080

#APP_NAME
spring:
  application:
    name: PRODUCT-SERVICE

#DATABASE
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_mem005?DB_CLOSE_DELAY=-1
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: false
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console

#URL      
microservice:
  product-service:
    endpoint:
      uri: http://PRODUCT-SERVICE/product
  category-service:
    endpoint:
      uri: http://CATEGORY-SERVICE/category      
