#APP_NAME
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NiteenRC/ikc-cloud-config-server

#PORT
server:
  port: 6001

#LOGGER
logging:
  level:
    root: warn
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

